### ISSUE TITLE
app repo not available

### ISSUE THREAD

**Issue by ranshe** [ARMmbed/reference-design-RD1168#2]
https://github.com/ARMmbed/reference-design-RD1168/blob/master/Documentation/RD1168_README.md asks the user to mbed import https://github.com/ARMmbed/reference-designs.git - but that import fails, as well as trying to visit https://github.com/ARMmbed/reference-designs (error: 404)

Please verify the URL and/or read permissions

import flow:
mbed import https://github.com/ARMmbed/reference-designs.git
[mbed] Importing program "reference-designs" from "https://github.com/ARMmbed/reference-designs.git" at latest revision in the current branch
Username for 'https://github.com': ranshe
Password for 'https://ranshe@github.com': 
[mbed] ERROR: Unable to clone repository (https://github.com/ARMmbed/reference-designs.git)

**Comment by ashok-rao** [comment]
Fixed by commit # 2cba5fb591b470a6c .. @ranshe  please check if this fixes the issue. Thanks.

Also, the https://github.com/ARMmbed/reference-designs is now public as well. You should be able to access this too. Thanks.
